spring:
  application:
    name: work-order-service-nosql
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://workorder_user:W0rk0rd3r_2026_@oficina-workorder.mia8qk5.mongodb.net/workorder_db?appName=oficina-workorder}

server:
  port: ${SERVER_PORT:8087}
  servlet:
    encoding:
      charset: UTF-8
      force: true

jwt:
  secret: ${JWT_SECRET:minha-chave-secreta-super-segura-para-jwt-com-256-bits-no-minimo}
  expiration-in-ms: ${JWT_EXPIRATION:3600000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  servers:
    - url: http://localhost:8087
      description: Local (MongoDB)
    - url: ${API_GATEWAY_BASE_URL:https://d9vqmoflh9.execute-api.us-east-2.amazonaws.com/dev}/work-order-nosql
      description: API Gateway