apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-order-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: work-order-service
          imagePullPolicy: Always
