apiVersion: v1
kind: ConfigMap
metadata:
  name: work-order-service-config
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8086"
  EUREKA_URL: "http://eureka-service:8761/eureka/"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  CUSTOMER_SERVICE_URL: "http://customer-service:8081"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT_URL: ""
