apiVersion: v1
kind: Secret
metadata:
  name: work-order-service-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:admin@mongodb:27017/workorder_db?authSource=admin"
  RABBITMQ_USERNAME: "oficina"
  RABBITMQ_PASSWORD: "oficina"
  INTERNAL_AUTH_TOKEN: ""
  JWT_SECRET: "change-me-at-least-32-chars-long-for-production"
