apiVersion: v1
kind: Service
metadata:
  name: work-order-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: work-order-service
  ports:
    - name: http
      port: 8086
      targetPort: http
